apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-ingress
  namespace: eks-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: app.mazin1hn.uk
    external-dns.alpha.kubernetes.io/target: aa53db17decd249e99009b5f49136b8c-279711686.eu-west-2.elb.amazonaws.com 
spec:
  ingressClassName: traefik

  rules:
    - host: app.mazin1hn.uk   
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clusterip-svc
                port:
                  number: 80

  tls:
    - hosts:
        - app.mazin1hn.uk
      secretName: eks-app-tls