apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

spec:
  source:
    repoURL: https://charts.jetstack.io 
    chart: cert-manager
    targetRevision: 1.19.3

    helm:
      values: |
        installCRDs: true