spec:
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/ 
    chart: external-dns
    targetRevision: 1.20.0

    helm:
      valueFiles:
        - helm/platform/external-dns/values.yaml