apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
spec:
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik-ingress
    targetRevision: 38.0.1

    